---
- hosts: kafka
  become: true
  vars:
    users_ssh_key_distribution:
      - 'ansible'
    rsa_name: cars_rsa
    localhost_replacer: jumpserver01
    localhost_mac: localhost
  
  tasks:
    - name: Scan And Register SSH Host Keys (hostname)
      command: "ssh-keyscan {{ item }}"
      register: "host_keys_hostname"
      changed_when: false
      with_items: "{{ groups['kafka'] }}"
      delegate_to: "{{ localhost_mac }}"
      become: false

    - name: Scan And Register SSH Host Keys (IP)
      command: "ssh-keyscan {{ hostvars[item]['ansible_host'] }}"
      register: "host_keys_ip"
      changed_when: false
      with_items: "{{ groups['kafka'] }}"
      delegate_to: "{{ localhost_mac }}"
      become: false

    - name: Write SSH Host Keys
      template:
        src: "ssh-hosts.j2"
        dest: "/etc/ssh/ssh_known_hosts"
      become: true

    - name: Capturing SSH Keys
      command: "cat /home/{{ item }}/.ssh/{{ rsa_name }}.pub"
      register: "_ssh_pub_key"
      become: true
      changed_when: false
      with_items: '{{ users_ssh_key_distribution }}'

    - name: Generating SSH Keys
      template:
        src: "ssh_keys_distribution.yml.j2"
        dest: "ssh_keys_distribution.yml"
      become: false
      run_once: true
      delegate_to: "{{ localhost_mac }}"

- hosts: kafka
  vars_files:
    - ./ssh_keys_distribution.yml
  tasks:
    - name: Adding SSH Keys
      authorized_key:
        user: "{{ item[1]['user'] }}"
        key: "{{ item[1]['key'] }}"
        state: "present"
      become: true
      with_subelements:
        - "{{ _ssh_keys_distribution }}"
        - keys
      when: inventory_hostname != item[0]['host']